### ISSUE TITLE
Missing files to be able to generate documentation

### ISSUE THREAD

**Issue by wcloetens** [BroadbandForum/cwmp-data-models#1]
The makefile refers to assets that are outside this repository.
```$ make -f makefile 
makefile:13: ../../install/etc/defs.mk: No such file or directory
makefile:152: ../../install/etc/rules.mk: No such file or directory
```
These seem absent from any of the BBF GitHub repositories.
They are presumably setting up rules to call Report_Tool/report.pl in the cwmp-xml-tools repository.

**Comment by wlupton** [comment]
This is true! The makefile is used for preparing the release but there is no intent that it be functional in the GH release.

I see that this is confusing, but I'm not sure that I want to remove the makefile from the release, because the fact is that the GH repo is identical to the internal repo in which the release is prepared.

A README file could explain this. Would that be sufficient?

**Comment by wcloetens** [comment]
I was looking for a way to generate data model documentation from XML source. I found what I wanted by using report.pl directly, so my use case is already addressed.
But, indeed, it is confusing. If this repository is publicly accessible, and includes the ability to generate a document bundle, with diffs, then making that functional would make sense. If there is no such intent, then yes, an explanation in the README, explaining the dependencies for those with internal repository access, and clarifying that generation is not functional without this access, would be lovely.

**Comment by wlupton** [comment]
OK. I'll think about it. As you will have seen, this makefile does more than just process the files in the current directory, it also imports the files from another (non-public) repo. But I like the idea of creating a standalone makefile that simply builds everything in the current directory (ideally with proper dependency checking!).

**Comment by wlupton** [comment]
The `makefile` is no longer released. I know this isn't ideal but it does address the original comment. So I'll close this (for now).
