### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by vladsadretdinov** [BroadbandForum/cwmp-data-models#2]
![Снимок экрана 2020-09-10 в 15 27 04](https://user-images.githubusercontent.com/5551873/92729491-12ca5b80-f37b-11ea-8841-64d40d7a7c4c.png)
![Снимок экрана 2020-09-10 в 15 27 53](https://user-images.githubusercontent.com/5551873/92729500-15c54c00-f37b-11ea-98bf-10d669c3864b.png)

This problem also occurs in tr-098 data model

**Comment by wlupton** [comment]
Thanks for the comment. This is correct, but I agree that the HTML presentation is confusing. It's a list of unsigned int but it's transported as a comma-separated list and is therefore a string at the protocol level. If you hover over the HTML you'll see "list(256) of unsignedInt" (which is just an English representation of what's in the XML).

<img width="196" alt="Screenshot 2020-09-10 at 14 08 37" src="https://user-images.githubusercontent.com/8874729/92733115-338cb400-f36f-11ea-881f-9767586a7583.png">
